on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  label-from-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: comment
        with:
          trigger: '/lgtm'
          prefix_only: true
          reaction: heart
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - run: |
          echo "${{steps.comment.outputs.triggered}}"
          echo "${{steps.comment.outputs.body}}"
      - uses: actions/github-script@v1
        if: steps.comment.outputs.triggered == 'true'
        with:
#          https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
#          Cannot trigger action if using GITHUB_TOKEN
          github-token: ${{secrets.LABEL_TOKEN}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['looks good to me']
            })