on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  label-from-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: comment
        with:
          trigger: '/lgtm'
          prefix_only: true
          reaction: heart
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - run: |
          echo "${{steps.comment.outputs.triggered}}"
          echo "${{steps.comment.outputs.body}}"
      - uses: actions/labeler@v2
        if: steps.comment.outputs.triggered == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"